ConsenSys/doc.tessera

- mkdocs.yml
Fix the Google search console verification id that was wrong (copy/paste error)
> fix search console id typo

- docs/Concepts/Transaction-manager.md
- docs/HowTo/Configure/KeyVault/Azure-Key-Vault.md
- docs/HowTo/Configure/KeyVault/Hashicorp-Vault.md
- docs/HowTo/Configure/Keys.md
- docs/HowTo/Configure/Override-config.md
- docs/HowTo/Configure/Tessera.md
- docs/HowTo/Configure/Transaction-manager.md
- docs/HowTo/Generate-keys.md
- docs/HowTo/MigrateFromConstellation.md
fix config md and some writing issues
Alphabetically order options
fixes #9 
See PR preview at https://pegasys-tessera--10.com.readthedocs.build/en/10/
> Docs migration fixes

- .circleci/config.yml
- tessera_rest_openapi3_spec.latest.yaml
Make the meaning of c11n explicit in REST API doc
No ticket created
> add c11n acronym description

- docs/Reference/REST-API.md
- update REST api doc link to target new GithubPages hosted doc.
- also trimmed end of line spaces.
fixes #7
> update API doc link

- README.md
- docs/Concepts/Transaction-manager.md
- docs/index.md
Fixed some typos and minor inconsistencies
> fixed typos

- .circleci/config.yml
- docs/Concepts/Enclave.md
- docs/Concepts/Transaction-manager.md
- docs/Concepts/p2p-discovery.md
- docs/HowTo/Configure/Enclave.md
- docs/HowTo/Configure/KeyVault/AWS-Secrets-Manager.md
- docs/HowTo/Configure/KeyVault/Azure-Key-Vault.md
- docs/HowTo/Configure/KeyVault/Hashicorp-Vault.md
- docs/HowTo/Configure/Keys.md
- docs/HowTo/Configure/Override-config.md
- docs/HowTo/Configure/TLS.md
- docs/HowTo/Configure/Tessera.md
- docs/HowTo/Configure/Transaction-manager.md
- docs/HowTo/Generate-keys.md
- docs/HowTo/MigrateFromConstellation.md
- docs/HowTo/Use/Logging.md
- docs/HowTo/Use/Monitoring.md
- docs/Reference/BootstrapSampleConfiguration.md
- docs/Reference/SampleConfiguration.md
- docs/index.md
Make vale and markdown lint tests pass
see PegaSysEng/Misc#26
Check https://pegasys-tessera--17.com.readthedocs.build/en/17/
> Make all quality tests pass

- .circleci/config.yml
- .markdownlintignore
- docs/Concepts/Enclave.md
- docs/Concepts/p2p-discovery.md
- docs/HowTo/Configure/Enclave.md
- docs/HowTo/Configure/KeyVault/Hashicorp-Vault.md
- docs/HowTo/Configure/Keys.md
- docs/HowTo/Configure/Override-config.md
- docs/HowTo/Configure/TLS.md
- docs/HowTo/Configure/Tessera.md
- docs/HowTo/Configure/Transaction-manager.md
- docs/HowTo/Generate-keys.md
- docs/HowTo/MigrateFromConstellation.md
- docs/HowTo/Use/Logging.md
- docs/HowTo/Use/Monitoring.md
- docs/Reference/BootstrapSampleConfiguration.md
- docs/Reference/REST-API.md
- docs/Reference/SampleConfiguration.md
- docs/index.md
- Update submodule and config to use new Vale2 guidelines checking tool.
- fix errors raised by this new version
see PegaSysEng/Misc#29
> Update to Vale2

- docs/HowTo/Configure/Tessera.md
Include enable privacy enhancement flag under features object.
> Move Privacy enhancement Flag under Features object in sample config

- docs/Tutorials/Quorum-Dev-Quickstart.md
- docs/index.md
- mkdocs.yml
> Added quickstart

- docs/HowTo/Use/Logging.md
Adding a couple more error messages to the docs from recent code release.
> Adding some extra error log messages.

- docs/Concepts/Enclave-types.md
- docs/Concepts/Enclave.md
- docs/Concepts/Transaction-manager.md
- docs/HowTo/Configure/Enclave.md
- mkdocs.yml
Edits to enclave concept and configuration content
> Edits to enclave concept and configuration content 

- docs/Concepts/Enclave-types.md
- docs/Concepts/Enclave.md
- docs/Concepts/Privacy-manager.md
- docs/Concepts/Transaction-manager.md
- docs/HowTo/Configure/Enclave.md
- docs/HowTo/Configure/Tessera.md
- docs/index.md
- mkdocs.yml
Reduce duplication, increase consistency, and update out-of-date info in the enclave pages.  
Additionally:
* Distinguish between Tessera (privacy manager) and its components (transaction manager and enclave)
* Attempt to clarify the different enclave jar considerations - eventually this will probably make more sense as part of a separate Distributions page
* Fix incorrect link in sidebar
* Fix invalid json samples
> [Enclave] Simplify & update

- docs/Concepts/p2p-discovery.md
- docs/HowTo/Configure/Peer-discovery.md
- docs/HowTo/Configure/Tessera.md
- mkdocs.yml
Improving peer discovery content
> Improving peer discovery content

- README.md
Update readme to Consensys repos and update badges
see ConsenSys/protocol-misc#187
> update readme and submodule

- docs/HowTo/Get-started/Dependencies.md
- docs/HowTo/Get-started/DistributionJar.md
- docs/HowTo/Get-started/Start-Tessera.md
- mkdocs.yml
> Added getting started content

- docs/HowTo/Configure/Tessera.md
Removed doc for previous versions
> Removed doc for previous versions

- docs/HowTo/Configure/Tessera.md
- docs/HowTo/Get-started/Dependencies.md
- docs/HowTo/Get-started/DistributionJar.md
- docs/HowTo/Get-started/Start-Tessera.md
* Fix broken UB encryptor link 
* Fix broken libsodium docs links
* Simplify Getting Started pages & reduce duplication
> Update broken links & simplify Getting Started pages

- docs/Tutorials/Migration-Multitenancy.md
- mkdocs.yml
Includes a guide on using the multi tenancy migration tool to combine two nodes from a single-tenant setup to a multi-tenancy setup.
**DRAFT until feature reaches Tessera master branch.**
Related PR: https://github.com/ConsenSys/tessera/pull/1190
> Add migration steps for combining Tessera nodes in a multitenant setup.

- docs/HowTo/Configure/Tessera.md
> fixed typo

- docs/HowTo/Configure/TLS.md
Update SslConfig to include clientAuth flag
> clientAuth flag in SslConfig

- docs/Concepts/Privacy-Groups.md
- docs/Concepts/Privacy-manager.md
- docs/Concepts/TesseraAPI.md
- docs/Concepts/Transaction-manager.md
- docs/HowTo/Get-started/DistributionJar.md
- docs/HowTo/Get-started/Start-Tessera.md
- docs/HowTo/Use/Logging.md
- docs/Reference/REST-API.md
- docs/index.md
- mkdocs.yml
Update GoQuorum to Ethereum client and mention Besu as a supported client.
#48
> Update GoQuorum to Ethereum client

- docs/HowTo/Configure/Tessera.md
- docs/Reference/SampleConfiguration.md
- mkdocs.yml
Documented the configuration file options in the reference section.
This forms part of a larger task to restructure the content.
> Add reference content for the configuration file.

- docs/HowTo/Get-started/Dependencies.md
Fix link to Oracle JDK download.
fixes ConsenSys/protocol-misc#277
> fix link to jdk download

- docs/HowTo/Configure/Tessera.md
- docs/HowTo/Generate-Keys/Generate-Keys.md
- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
- mkdocs.yml
Signed-off-by: Byron Gravenorst <byron.gravenorst@consensys.net>
Add documentation for the Tessera command line options and subcommands.
Fixes #65
> Add Tessera command line options.

- docs/HowTo/Configure/Keys/Overview.md
- docs/HowTo/Configure/Keys/Secure-Keys.md
- docs/HowTo/Configure/Override-config.md
- docs/HowTo/Configure/Tessera.md
- docs/HowTo/Generate-Keys/AWS-Secrets-Manager.md
- docs/HowTo/Generate-Keys/Azure-Key-Vault.md
- docs/HowTo/Generate-Keys/File-Stored-Keys.md
- docs/HowTo/Generate-Keys/Hashicorp-Vault.md
- docs/Reference/CLI/CLI-Subcommands.md
- mkdocs.yml
Signed-off-by: Byron Gravenorst <byron.gravenorst@consensys.net>
Add links to reference content.
Fixes #68
> Add links to reference content.

- docs/HowTo/Migrate/MigrateFromOrion.md
- mkdocs.yml
This PR adds stub content for migrating from Orion to Tessera in addition to a link to the full content.
> Added stub content and link for migrating from Orion to Tessera

- docs/HowTo/Get-started/Start-Tessera.md
Ensure naming of config file is consistent throughout documentation.
fixes #69
> make config file naming consistent

- docs/HowTo/Configure/TLS.md
Add note on TLS config when using multiple endpoints.
fixes #75
> add note on TLS config when using multiple endpoints

- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
- mkdocs.yml
Update CLI and subcommand pages for clarity and consistency.
Alphabetize.
Add "version" and "help" options.
fixes #87
> update cli and subcommand pages

- docs/Reference/SampleConfiguration.md
syntax error in sample config file
fixes issue #92
> syntax error in cors config

- docs/HowTo/Configure/Database.md
- docs/HowTo/Configure/KeyVault/Azure-Key-Vault.md
- docs/HowTo/Get-started/Docker-Images.md
- mkdocs.yml
* Add Docker page to Getting Started section
* Update Azure configuration documentation for the latest version of Tessera which replaces deprecated Azure client library
> Docker and azure updates

- docs/HowTo/Get-started/Build-From-Source.md
Update the command to verify build success.
> build from source: update cmdline

- mkdocs.yml
Redirects are missing in the project config
I looked through all the config history to add all required redirects
I updated submodule
Broken link detected on Besu doc project:
https://app.circleci.com/pipelines/github/hyperledger/besu-docs/2814/workflows/f61bc35f-f425-4078-9ce0-b89bf54acea5/jobs/12221
> add redirect for deleted page

- docs/HowTo/Get-started/Distribution.md
> update install command lines

- docs/HowTo/Use/Monitoring.md
Update monitoring page to remove "Creating a Grafana Dashboard" content and replace with link to GoQuorum dashboard. Also edit the rest of the page.
fixes #81 
see https://pegasys-tessera--108.com.readthedocs.build/en/108/HowTo/Use/Monitoring/
> update monitoring page

- docs/HowTo/Configure/Multiple-private-state.md
- docs/HowTo/Migrate/Migration-Multitenancy.md
Minor edits to multi-tenancy content (after [updates to GoQuorum multi-tenancy content](https://github.com/ConsenSys/doc.goquorum/pull/156)).
fixes #110
> minor updates to multi-tenancy content

- docs/HowTo/Configure/Keys/Overview.md
- docs/HowTo/Configure/Tessera.md
- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
* Update `configfile` to include alias `config-file`
*  fix incorrect link
fixes #115 
https://pegasys-tessera--118.com.readthedocs.build/en/118/Reference/CLI/CLI-Syntax/#configfile-config-file
> Update configfile to include config-file

- docs/HowTo/Get-started/Distribution.md
- docs/HowTo/Use/Logging.md
Update to American spelling
Fixes #117 
https://pegasys-tessera--120.com.readthedocs.build/en/120/
> Update to American spelling

- docs/Concepts/Multitenancy.md
- docs/HowTo/Configure/Multiple-private-state.md
- docs/HowTo/Migrate/Migration-Multitenancy.md
- mkdocs.yml
Add page on Tessera/GoQuorum multi-tenancy, linking to existing GoQ content.
fixes #42 
https://pegasys-tessera--122.com.readthedocs.build/en/122/Concepts/Multitenancy/
> doc multi-tenancy

- docs/HowTo/Configure/High-availability.md
- docs/HowTo/Configure/Override-config.md
- docs/HowTo/Configure/Peer-discovery.md
- docs/HowTo/Configure/TLS.md
- docs/HowTo/Configure/Tessera.md
Update How To > Configure content as needed for clarity and style. Most heavy updates to https://pegasys-tessera--134.com.readthedocs.build/en/134/HowTo/Configure/TLS/.
fixes #126
> update configuration content

- docs/HowTo/Configure/KeyVault/AWS-Secrets-Manager.md
- docs/HowTo/Configure/KeyVault/Azure-Key-Vault.md
- docs/HowTo/Configure/KeyVault/Hashicorp-Vault.md
- docs/HowTo/Configure/Keys/AWS-Secrets-Pairs.md
- docs/HowTo/Configure/Keys/Azure-Key-Vault-Pairs.md
- docs/HowTo/Configure/Keys/File-Based-Key-Pairs.md
- docs/HowTo/Configure/Keys/Hashicorp-Vault-Pairs.md
- docs/HowTo/Configure/Keys/Overview.md
- docs/HowTo/Generate-Keys/AWS-Secrets-Manager.md
- docs/HowTo/Generate-Keys/Azure-Key-Vault.md
- docs/HowTo/Generate-Keys/File-Stored-Keys.md
- docs/HowTo/Generate-Keys/Generate-Keys.md
- docs/HowTo/Generate-Keys/Hashicorp-Vault.md
- mkdocs.yml
Update generate/configure keys content for clarity and style. Add links between related content.
fixes #125
> update generate/configure keys content

- docs/HowTo/Use/Logging.md
- docs/HowTo/Use/Mandatory-Recipients.md
- docs/HowTo/Use/Monitoring.md
Update content under How to > Use, including monitoring and logging pages.
fixes #127
> update use content

- docs/Concepts/Multitenancy.md
- docs/Concepts/Privacy-Manager/Transaction-manager.md
- docs/Tutorials/Quorum-Dev-Quickstart.md
Minor updates to quickstart and two concept pages.
fixes #128 
fixes #129
> update quickstart and concepts

- docs/Reference/CLI/CLI-Subcommands.md
- docs/Reference/CLI/CLI-Syntax.md
Updates CLI subcommand and syntax page to match stylistically.
Fixes #131
> Update CLI subcommand introduction

- docs/HowTo/Configure/TesseraAPI.md
- docs/HowTo/Get-started/Start-Tessera.md
- docs/HowTo/Use/Monitoring.md
- docs/Reference/BootstrapSampleConfiguration.md
This flag has been deprecated for quite some time
> [MINOR] remove enabled flag from server configs

- README.md
- mkdocs.yml
Made repo name consistent with other ConsenSys product docs
> ConsenSys case

- docs/HowTo/Get-started/Use-GoQuorum-with-Tessera.md
Update broken GoQuorum links.
Fixes #144
> Update broken GoQuorum links

- mkdocs.yml
Changed GoQuorum to Tessera in the header
> Changed GoQuorum to Tessera in the header

- .github/pull_request_template.md
Updated the PR template to match GoQuorum
> updated info in PR template

- docs/Concepts/p2p-discovery.md
- docs/HowTo/Configure/Peer-discovery.md
See https://github.com/ConsenSys/tessera/issues/1394
> added more info and scenario for startup

- docs/HowTo/Configure/Database.md
- docs/HowTo/Migrate/Upgrade.md
- mkdocs.yml
Use the following template to make sure your PR fits the Tessera documentation standard.
Add documentation for updating and migrating the database.
Fixes #151 
Fixes #150 
For content changes:
For tool changes:
and added a [preview link](#preview).
https://pegasys-tessera--153.com.readthedocs.build/en/153/HowTo/Configure/Database/#upgrade-the-database
> Document upgrading the database

- docs/HowTo/Configure/TLS.md
Use the following template to make sure your PR fits the Tessera documentation standard.
Clarify which server uses which TLS configuration options
Fixes #152 
For content changes:
For tool changes:
and added a [preview link](#preview).
> Clarify client/server TLS configuration

- docs/HowTo/Configure/TLS.md
Clarify `ENCLAVE` TLS is client and server instead of client only
See #154 
For content changes:
For tool changes:
and added a [preview link](#preview).
> Clarify enclave TLS configuration

- docs/HowTo/Configure/TLS.md
- docs/Reference/SampleConfiguration.md
Use the following template to make sure your PR fits the Tessera documentation standard.
Add `sslConfigType` config item
Clarify TLS with `sslConfigType`
Fixes #156 
For content changes:
For tool changes:
and added a [preview link](#preview).
https://pegasys-tessera--157.com.readthedocs.build/en/157/Reference/SampleConfiguration/
https://pegasys-tessera--157.com.readthedocs.build/en/157/HowTo/Configure/TLS/
> Add `sslConfigType` config item

- .circleci/config.yml
- docs/Reference/TesseraAPI.md
Use the following template to make sure your PR fits the Tessera documentation standard.
Updated Incorrect Link
Fixes #161
> Updated Incorrect Link
